### ISSUE TITLE
keybindings not working/responding(?) (tested in a VM)

### ISSUE THREAD

**Issue by IPushedU** [jbuchermn/newm#103]
After a bit of struggling with getting everything set up and installed correctly (first time doing something like this,i.e. from scratch cli arch install and installing a wm, so I wasn't expecting a smooth trip but everything worked at the end, forgive my noobiness), I got newm to work because I really wanted to try it out since the first time I found about it on the arch wiki. I wanted to try newm first in a vm (virtualbox), its launches fine form the tty and the animations are working smoothly, pressing the mod/logo key zooms in/out smoothly but mod/logo + enter doesnt launch alcritty although i have installed it explicitly. How can I test to seee if the keybindings are being read or even being registered? Or is it a problem with the combination of virtualbox and newm? Thanks for your help.

**Comment by jbuchermn** [comment]
Hey,

I haven't been able to get it running properly on VirtualBox. From the looks of it, VirtualBox are not interested at all in properly supporting a recent OpenGL version - that's why Alacritty does not even start up, and the animations look bad.

To verify that, I suggest you install sway alongside and test Alacritty inside sway - that way I can rule out it's a newm bug.

Apart form that: I suggest using qemu with virgl, on which sway and newm work. This however can be a bit of a hassle to set up depending on your host system (if you're on macOS, thankfully there's a homebrew package).

**Comment by IPushedU** [comment]
Hi, thanks for the quick response. 
Following the advice in this issue #55, I installed sway first as a sanity check and to check if it's possible in virtualbox and then installed newm, and the same problem existed in sway too but I thought it was in my installation. I didn't know it was caused by virtualbox and OpenGL themselves, thanks for your insight, now I don't have to troubleshoot. And also thanks for the suggestion of qemu with virgl, I have never touched qemu til now but I'll give it a shot on Windows, anything to get newm to work cus I've been really intrigued by it. (you may close this issue, I think it's resolved. I'll also give an update if the qemu thing worked out.)
