### ISSUE TITLE
I can't click on popup

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#13]
I'm testing applications, when I open datagrid or any jetbrans ide I can't click about your pop-ups

**Comment by jbuchermn** [comment]
Yup I've encountered this as well. Unfortunately Java is lagging behind in this regard a lot (as far as I know doesn't support native wayland at all). sway manages to make xwayland jetbrains behave okay, but there's a lot of custom coding for this app (as far as I can tell). I've decided to not introduce such changes for any xwayland app (really the issue is Java here, not any compositor). 

Here: https://wiki.openjdk.java.net/display/wakefield They actually consider native Wayland support a "medium to long time" goal...

I'll check soon if this has gotten any better, but probably not.

**Comment by CRAG666** [comment]
I no longer buy this product, I will look for other native alternatives

**Comment by jbuchermn** [comment]
Closing this for now.
