### ISSUE TITLE
Chromium based web browsers don't work

### ISSUE THREAD

**Issue by ibrahimbayyinah** [jbuchermn/newm#24]
I installed Brave and Chromium. Both of them don't work. When I try to run them from the terminal, I just get the output:
```Trace/breakpoint trap```

Do you know what the problem is? It's running on Artix Linux on a ThinkPad X220 (yes I'm the same person).

Both web browsers work under sway.

Thanks in advance.

**Comment by ibrahimbayyinah** [comment]
I just tried Firefox. It works. I wonder why the chromium based browsers don't work.

**Comment by ibrahimbayyinah** [comment]
Thanks!

As a sidenote: I read on #10 that the person compiled v2. So now I am wondering: is it better to install newm from the AUR or is it better to compile it from github? Or does it not matter which option one chooses?

I am very excited about this project. It seems like a really cool compositor that would fit nicely with my workflow. I am a nooby Python programmer. Is there anything I can do to help?

**Comment by CRAG666** [comment]
As for the compilation, if you can do it with the PKBUILD, you only need to clones newm and pywm in the same directory, applying the patches to pywm. This is better than doing it from github because you have control of the package with pacman. This I had already said but the creator of the package should check the build because it does not generate the correct version and this makes the package always marked as outdated

**Comment by jbuchermn** [comment]
> As a sidenote: I read on #10 that the person compiled v2. So now I am wondering: is it better to install newm from the AUR or is it better to compile it from github? Or does it not matter which option one chooses?

v0.2 is still work in progress, that's why you can't get it from the AUR. There are some bugs to be fixed and missing features before I'll release v0.2 updating the AUR package. However, if you're interested (e.g. you need multiple monitors) I suggest you try it out. The easiest way is to install via pip (see README).

Once v0.2 is ready, the AUR package will be updated.

> I am very excited about this project. It seems like a really cool compositor that would fit nicely with my workflow. I am a nooby Python programmer. Is there anything I can do to help?

I'm always happy if people want to contribute. Config (and documentation of config) can always be improved and I think it's a good starting point. Take a look at all the config options in README and find all usages of configured_value in the project. Also if you're missing documentation on certain aspects, feel free to report bugs or start adding information yourself.
